### ISSUE TITLE
[Bug]: divider not dividing correctly

### ISSUE THREAD

**Issue by Jomyy** [SwiftcordApp/Swiftcord#100]
### Describe the Bug

server bar goes beyond divider 

it shouldn't do that

### Reproducing the Bug

do nothing

### Version

0.4.5

### Category

Other

### Screenshots

<img width="198" alt="Bildschirmfoto 2022-08-14 um 11 02 26" src="https://user-images.githubusercontent.com/62953110/184529948-5984bf2f-e2d3-4efa-844d-2aa5923c24d5.png">

**Comment by cryptoAlgorithm** [comment]
@Jomyy What macOS versions are you running on?

**Comment by Jomyy** [comment]
Monterey 12.4

**Comment by cryptoAlgorithm** [comment]
<img width="598" alt="Screenshot 2022-08-14 at 6 21 16 PM" src="https://user-images.githubusercontent.com/64193267/184532569-e7085b7b-9324-437e-8086-1b1596a37f55.png">
When you aren't hovering on the toolbar, does the lighter divider (over the server and channel list) align with the darker divider (over the message list)? If it does, this is a known issue that I have tried to fix, and can't fix due to some macOS (or rather SwiftUI) nonsense. I'm using different offsets for macOS 12 and 13, since the behaviour is different for some reason.

<img width="598" alt="Screenshot 2022-08-14 at 6 23 47 PM" src="https://user-images.githubusercontent.com/64193267/184532649-cb35a0cf-97d2-4250-8720-0441e4051ef6.png">

On macOS 13, the black divider that appears on hover is misaligned since SwiftUI seems to be adding a padding to that system divider. I can't fix that, if thats whats happening here.

**Comment by cryptoAlgorithm** [comment]
This issue will be closed as no further response was received from the OP.
