### ISSUE TITLE
Visual glitch in the traffic lights area

### ISSUE THREAD

**Issue by Vfposselt** [SwiftcordApp/Swiftcord#129]
Hi all,

The following glitch happens with either the dark and light themes:

<img width="513" alt="Untitled (6)" src="https://user-images.githubusercontent.com/80127724/205493959-27ad302b-9a68-4720-abf9-82107aa10b37.png">
<img width="403" alt="Untitled (5)" src="https://user-images.githubusercontent.com/80127724/205493962-5c5eb17e-b181-42a2-b319-a47cc267a40e.png">

Happens with alpha release, both standalone and brew versions. Also happens when in fullscreen mode as well. Tried reinstalling but the glitch persists. Is anyone experiencing the same glitch?

**Comment by PiemanAU** [comment]
I am also experiencing this

**Comment by cryptoAlgorithm** [comment]
Yeah, this glitch occurs due to the way I've implemented blur in that area. It only appears if scrollbars are set to always be visible, though. A fix for this (and much more) is being worked on in the #i-am-speed branch.

**Comment by Vfposselt** [comment]
> Yeah, this glitch occurs due to the way I've implemented blur in that area. It only appears if scrollbars are set to always be visible, though. A fix for this (and much more) is being worked on in the #i-am-speed branch.

Thanks for all your work, first of all! Second, I did not have scroll bar always set to visible when I read your comment, which made me curious. Turns out that the bug doesn't show on my MacBook screen when scrollbar is not set to always visible, but it shows up on my external monitor with either scrollbar always visible or not. 

Also, I remember this bug would not show on dark mode on past versions, while it did appear in light mode.

**Comment by cryptoAlgorithm** [comment]
Thanks! Yeah, just ignore this bug for the moment because it's impossible for me to fix it with the current way it's implemented. However, you're not alone in finding this annoying, so I've already fixed this and more in the `i-am-speed` branch. 

Here's how it looks on that branch: 
![](https://media.discordapp.net/attachments/964741354536194099/1033025466136789022/Screenshot_2022-10-21_at_10.33.33_PM.png)

Note how the whole toolbar is one continuous blurred region, compared to the older versions where the area above the message history had its own blur. 

However, I don't recommend using the `i-am-speed` as there are still pretty serious message history and event handling bugs in there. Thanks again for using Swiftcord!

**Comment by freepicheep** [comment]
@Vfposselt, maybe you learned this by now, but if you are using a mouse with your Mac, the scrollbars are always set to visible. Apple really needs to give you the option to disable this because it's very annoying.

**Comment by cryptoAlgorithm** [comment]
Fixed with merge from `devel` -> `main`. 

Here's how the UI looks as of the latest commit:
<img width="1549" alt="Screenshot 2023-02-26 at 8 50 02 PM" src="https://user-images.githubusercontent.com/64193267/221411440-b5fb5b3f-d7ad-41c8-9c04-cb99d97d6c7d.png">
