### ISSUE TITLE
[Bug]: Channel list scrollbar too large

### ISSUE THREAD

**Issue by Sjmarf** [SwiftcordApp/Swiftcord#147]
**Bug Description**
Channel list scrollbar extends into the window toolbar header

**Expected Behavior**
Scrollbar should terminate before the header

### Version

0.6.1

### Category

Other

### Screenshots

<img width="181" alt="image" src="https://github.com/SwiftcordApp/Swiftcord/assets/78750526/1b4228a3-8e17-435f-9ac0-2a53bd0601a9">

**Comment by cryptoAlgorithm** [comment]
<img width="356" alt="Screenshot 2023-11-09 at 11 49 04 PM" src="https://github.com/SwiftcordApp/Swiftcord/assets/64193267/e532c07d-69f3-4841-9523-95156d75fe5e">

Fixed with Sonoma UI overhaul. A side effect of this is that the UI might appear slightly broken on older macOS versions still supported by Swiftcord.
