### ISSUE TITLE
[Bug]: in app update doesn't find latest release

### ISSUE THREAD

**Issue by ixje** [SwiftcordApp/Swiftcord#148]
### Describe the Bug

**Bug Description**
The `0.6.1` release has been out for 2 days by now, but my `0.5.1` install can't find it.

**Actual Behaviour**
in app update thinks 0.5.1 is the latest version

**Expected Behavior**
in app update to find 0.6.1 version and be able to update from there

### Version

0.5.1

### Category

Other

### Screenshots

<img width="1791" alt="Screenshot 2023-05-12 at 08 24 08" src="https://github.com/SwiftcordApp/Swiftcord/assets/6625537/584c0909-108f-45b0-8aa6-a03be710d28c">

Note the date in the upper right corner compared to the latest release found

**Comment by cryptoAlgorithm** [comment]
Thanks for reporting this! However, this is expected as the sparkle appcast has yet to be updated, hence it is not yet possible to autoupdate to v0.6.1. This is to verify the release is stable and doesn't contain unexpected bugs (by observing helpful AppCenter crash analytics) since the jump from v0.5.1 to v0.6.1 is huge. If everything goes according to plan, this release is expected to be available thru autoupdate in the next day or so.

**Comment by ixje** [comment]
As long as it is expected, then all is good :+1:

**Comment by cryptoAlgorithm** [comment]
@ixje It should now be possible to auto-update to v0.6.1 from v0.5.1!
