### ISSUE TITLE
[Enhancement]: GIFs not rendered

### ISSUE THREAD

**Issue by aceilort** [SwiftcordApp/Swiftcord#68]
version 0.4.1

**Describe the bug**

I checked on servers and in my DMs, but when someone sends a GIF, only the URL is displayed with a block underneath it. You can still click on the link to view the GIF in your browser, but needless to say, this is not the best solution :,)

<img width="666" alt="Screen Shot 2022-06-19 at 10 58 49 PM" src="https://user-images.githubusercontent.com/31285382/174500130-74b73a9b-db7b-4cc3-b772-7c982af9be91.png">

**Comment by cryptoAlgorithm** [comment]
Hi there! This isn't a _really_ a bug, rather it's a missing feature. Currently, animated servers icons/profile images aren't displayed, since `SwiftUI.Image`/`NSImage` doesn't support rendering GIFs whatsoever. However, the empty embed being rendered is a bug, and will be fixed.

In the future, gif rendering will be added either thru a custom implementation or using an existing package. 

Thanks for the issue!

**Comment by cryptoAlgorithm** [comment]
Update: @Candygoblen123 is currently working on an implementation with SwiftyGif

**Comment by cryptoAlgorithm** [comment]
Efforts to add GIF rendering with `SwiftyGif` are being worked on at the `gif` branch

**Comment by cryptoAlgorithm** [comment]
Update: DIscord's "GIF" embeds from sources like Tenor are actually videos. Hence, rendering these types of embeds might not be supported even after the gif branch gets merged.

**Comment by cryptoAlgorithm** [comment]
The GIF branch has been merged, closing this issue. However, GIF embed support isn't added, due to issues stated in the PR (#92)
